version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PROD_ROOT_PASSWORD}
      MYSQL_DATABASE: zahoot
      MYSQL_USER: backend
      MYSQL_PASSWORD: ${MYSQL_PROD_PASSWORD}
    volumes:
    - zahoot_data:/var/lib/mysql
    networks:
      - zahoot-network
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://backend:${MYSQL_PROD_PASSWORD}@db:3306/zahoot
      JWT_SECRET: ${JWT_PROD_SECRET}
    ports:
      - "3000:3000"
volumes:
  zahoot_data:
networks:
  zahoot-network: